/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz_2;

/**
 *
 * @author Sergio
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        jTextAreaDescripcion.append("Mi nombre es : Sergio Marco \n\n Mis aficiones son: \n*Disfrutar de la familia\n*Aprender cosas nuevas"
                + "\n*Jugar al fútbol\n*Programar\n*Jugar a Videojuegos\n*Disfrutar la vida\n"
                + "\nMi cumpleaños es: 21 de Mayo");
        jTextAreaDescripcion.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanePestañas = new javax.swing.JTabbedPane();
        jPanelPresentacion = new javax.swing.JPanel();
        jButtonFormulario = new javax.swing.JButton();
        jButtonConvertidor = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jPanelFormulario = new javax.swing.JPanel();
        jPanelConvertidor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonFormulario.setText("Formulario");
        jButtonFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFormularioActionPerformed(evt);
            }
        });

        jButtonConvertidor.setText("Cambio de moneda");
        jButtonConvertidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertidorActionPerformed(evt);
            }
        });

        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setRows(5);

        javax.swing.GroupLayout jPanelPresentacionLayout = new javax.swing.GroupLayout(jPanelPresentacion);
        jPanelPresentacion.setLayout(jPanelPresentacionLayout);
        jPanelPresentacionLayout.setHorizontalGroup(
            jPanelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPresentacionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jTextAreaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonConvertidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );
        jPanelPresentacionLayout.setVerticalGroup(
            jPanelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPresentacionLayout.createSequentialGroup()
                .addGroup(jPanelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPresentacionLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonFormulario)
                        .addGap(23, 23, 23)
                        .addComponent(jButtonConvertidor))
                    .addGroup(jPanelPresentacionLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jTextAreaDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonCerrar)
                .addGap(24, 24, 24))
        );

        jTabbedPanePestañas.addTab("Presentación", jPanelPresentacion);

        javax.swing.GroupLayout jPanelFormularioLayout = new javax.swing.GroupLayout(jPanelFormulario);
        jPanelFormulario.setLayout(jPanelFormularioLayout);
        jPanelFormularioLayout.setHorizontalGroup(
            jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );
        jPanelFormularioLayout.setVerticalGroup(
            jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );

        jTabbedPanePestañas.addTab("Formulario", jPanelFormulario);

        javax.swing.GroupLayout jPanelConvertidorLayout = new javax.swing.GroupLayout(jPanelConvertidor);
        jPanelConvertidor.setLayout(jPanelConvertidorLayout);
        jPanelConvertidorLayout.setHorizontalGroup(
            jPanelConvertidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );
        jPanelConvertidorLayout.setVerticalGroup(
            jPanelConvertidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );

        jTabbedPanePestañas.addTab("Convertidor", jPanelConvertidor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePestañas, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPanePestañas)
                .addContainerGap())
        );

        jTabbedPanePestañas.getAccessibleContext().setAccessibleName("Presentacion");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFormularioActionPerformed
        jTabbedPanePestañas.setEnabledAt(1,true);
        jTabbedPanePestañas.setSelectedIndex(1);
    }//GEN-LAST:event_jButtonFormularioActionPerformed

    private void jButtonConvertidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertidorActionPerformed
jTabbedPanePestañas.setEnabledAt(2,true);
        jTabbedPanePestañas.setSelectedIndex(2);    }//GEN-LAST:event_jButtonConvertidorActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonConvertidor;
    private javax.swing.JButton jButtonFormulario;
    private javax.swing.JPanel jPanelConvertidor;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JPanel jPanelPresentacion;
    private javax.swing.JTabbedPane jTabbedPanePestañas;
    private javax.swing.JTextArea jTextAreaDescripcion;
    // End of variables declaration//GEN-END:variables
}
